image: androidsdk/android-30

pipelines:
  pull-requests:
    '**':
      - step:
          name: Unit Test
          size: 2x
          caches:
            - gradle
          script:
            - ./gradlew :app:testHuaweiQaDebugUnitTest