image: androidsdk/android-30

pipelines:
  default:
    - parallel:
        steps:
          - step:
              name: Lint
              caches:
                - gradle
              script:
                - ./gradlew lint
              artifacts:
                - app/build/reports/**
          - step:
              name: Unit Test
              caches:
                - gradle
              script:
                - ./gradlew :app:testHuaweiQaDebugUnitTest