image: androidsdk/android-30

pipelines:
  default:
    - step:
        name: Unit Test
        size: 2x
        caches:
          - gradle
        script:
          - ./gradlew :app:testHuaweiQaDebugUnitTest