image: androidsdk/android-30

pipelines:
  default:
    - parallel:
        - step:
            name: Lint
            caches:
              - gradle
            script:
              - ./gradlew lint
            artifacts:
              - app/build/reports/**
        - step:
            name: Huawei QA Unit Test
            caches:
              - gradle
            script:
              - ./gradlew :app:testHuaweiQaDebugUnitTest
        - step:
            name: Google QA Unit Test
            caches:
              - gradle
            script:
              - ./gradlew :app:testGoogleQaDebugUnitTest