image: androidsdk/android-30

pipelines:
  default:
    - parallel:
        - step:
            name: Assemble Huawei QA Debug
            caches:
              - gradle
            script:
              - ./gradlew assembleHuaweiQaDebug
            artifacts:
              - app/build/outputs/**
        - step:
            name: Lint
            caches:
              - gradle
            script:
              - ./gradlew lint
            artifacts:
              - app/build/reports/**
        - step:
            name: Huawei QA Debug Unit Test
            caches:
              - gradle
            script:
              - ./gradlew :app:testHuaweiQaDebugUnitTest