package za.co.woolworths.financial.services.android.ui.wfs.theme

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

class Dimensions(
    val oneDp: Dp,
    val dp24: Dp,
    val icon_size_dp: Dp,
    val thirty_one_dp: Dp,
    val thirty_two_dp: Dp,
    val twelve_sp: TextUnit,
    val sixteen_sp: TextUnit,
    val twenty_three_dp: Dp,
    val eighteen_sp: TextUnit,
    val thirteen_sp: TextUnit,
    val ten_sp: TextUnit,
    val fifty_seven_dp: Dp,
    val sixty_dp: Dp,
    val eighty_dp: Dp,
    val eight_dp: Dp,
    val sixteen_dp: Dp,
    val zero_sp: TextUnit,
    val one_sp: TextUnit,
    val point_five_sp: TextUnit,
    val ten_dp: Dp,
    val six_dp: Dp,
    val four_dp: Dp,
    val fourteen_sp: TextUnit,
    val fifteen_sp: TextUnit,
    val thirty_six_dp: Dp,
    val twenty_sp: TextUnit,
    val fifty_dp: Dp,
    val eighty_five_dp: Dp,
    val twenty_six_dp: Dp,
    val fifteen_dp: Dp,
    val seven_dp: Dp,
    val five_dp: Dp,
    val zero_dp: Dp,
    val three_dp: Dp,
    val twenty_dp: Dp,
    val two_dp: Dp,
    val twelve_dp: Dp,
    val letterspacing_029_sp : TextUnit,
    val thirteen_dp: Dp,
    val hundredSeventyDp: Dp,
    val pull_to_refresh_trigger_distance_dp: Dp,
    val pull_to_refresh_offset_dp: Dp,
    val account_landing_my_offers_image_height_dp : Dp,
    val button_height_twenty_six_dp : Dp,
    val fourteen_dp : Dp,
    val thirty_four_dp: Dp = 34.dp,
    val forty_dp: Dp = 40.dp,
    val fourteen_dp : Dp,
    val eighteen_dp : Dp,
    val one_twenty_dp : Dp,
    val point_five_dp : Dp,
    val one_point_five_sp : TextUnit

)

val sw320Dimensions = Dimensions(
    oneDp = 1.dp,
    letterspacing_029_sp = 0.29.sp,
    dp24 = 24.dp,
    thirty_one_dp = 31.dp,
    thirty_two_dp = 32.dp,
    twelve_sp = 12.sp,
    thirteen_sp = 13.sp,
    ten_sp = 10.sp,
    sixteen_sp = 16.sp,
    twenty_three_dp = 23.dp,
    eighteen_sp = 18.sp,
    fifty_seven_dp = 57.dp,
    sixty_dp = 60.dp,
    eighty_dp = 80.dp,
    eight_dp = 8.dp,
    sixteen_dp = 16.dp,
    zero_sp = 0.sp,
    one_sp = 1.sp,
    point_five_sp = 0.5.sp,
    ten_dp = 10.dp,
    six_dp = 6.dp,
    four_dp = 4.dp,
    fourteen_sp = 14.sp,
    fifteen_sp = 15.sp,
    thirty_six_dp = 36.dp,
    twenty_sp = 20.sp,
    fifty_dp = 50.dp,
    eighty_five_dp = 85.dp,
    twenty_six_dp = 26.dp,
    fifteen_dp = 15.dp,
    seven_dp = 7.dp,
    five_dp = 5.dp,
    zero_dp = 0.dp,
    three_dp = 3.dp,
    twenty_dp = 20.dp,
    icon_size_dp = 24.dp,
    two_dp = 2.dp,
    twelve_dp = 12.dp,
    thirteen_dp = 13.dp,
    hundredSeventyDp = 170.dp,
    pull_to_refresh_trigger_distance_dp = 100.dp,
    pull_to_refresh_offset_dp = 60.dp,
    account_landing_my_offers_image_height_dp = 152.dp,
    button_height_twenty_six_dp = 25.dp,
    fourteen_dp = 14.dp,
    eighteen_dp = 18.dp,
    one_twenty_dp = 120.dp,
    point_five_dp = 0.5.dp,
    one_point_five_sp = 1.5.sp
)

val sw360Dimensions = Dimensions(
    oneDp = 1.dp,
    dp24 = 24.dp,
    thirty_one_dp = 31.dp,
    letterspacing_029_sp = 0.29.sp,
    thirty_two_dp = 32.dp,
    icon_size_dp = 25.dp,
    twelve_sp = 12.sp,
    thirteen_sp = 13.sp,
    ten_sp = 10.sp,
    sixteen_sp = 16.sp,
    twenty_three_dp = 23.dp,
    eighteen_sp = 18.sp,
    fifty_seven_dp = 57.dp,
    sixty_dp = 60.dp,
    eighty_dp = 80.dp,
    eight_dp = 8.dp,
    sixteen_dp = 16.dp,
    zero_sp = 0.sp,
    one_sp = 1.sp,
    point_five_sp = 0.5.sp,
    ten_dp = 10.dp,
    six_dp = 6.dp,
    four_dp = 4.dp,
    fourteen_sp = 14.sp,
    fifteen_sp = 15.sp,
    thirty_six_dp = 36.dp,
    twenty_sp = 20.sp,
    fifty_dp = 50.dp,
    eighty_five_dp = 85.dp,
    twenty_six_dp = 26.dp,
    fifteen_dp = 15.dp,
    seven_dp = 7.dp,
    five_dp = 5.dp,
    zero_dp = 0.dp,
    three_dp = 3.dp,
    twenty_dp = 20.dp,
    two_dp = 2.dp,
    twelve_dp = 12.dp,
    thirteen_dp = 13.dp,
    hundredSeventyDp = 170.dp,
    pull_to_refresh_trigger_distance_dp = 100.dp,
    pull_to_refresh_offset_dp = 60.dp,
    account_landing_my_offers_image_height_dp = 172.dp,
    button_height_twenty_six_dp = 26.dp,
    fourteen_dp = 14.dp,
    eighteen_dp = 18.dp,
    one_twenty_dp = 120.dp,
    point_five_dp = 0.5.dp,
    one_point_five_sp = 1.5.sp
)

val sw400Dimensions = Dimensions(
        oneDp = 1.dp,
        dp24 = 24.dp,
        thirty_one_dp = 31.dp,
    letterspacing_029_sp = 0.29.sp,
    thirty_two_dp = 32.dp,
        icon_size_dp = 25.dp,
        twelve_sp = 12.sp,
        sixteen_sp = 16.sp,
        twenty_three_dp = 23.dp,
        eighteen_sp = 18.sp,
        fifty_seven_dp = 57.dp,
        sixty_dp = 60.dp,
        eighty_dp = 80.dp,
        eight_dp = 8.dp,
        sixteen_dp = 16.dp,
        zero_sp = 0.sp,
        one_sp = 1.sp,
        point_five_sp = 0.5.sp,
        ten_dp = 10.dp,
        six_dp = 6.dp,
        four_dp = 4.dp,
        thirteen_sp = 13.sp,
        ten_sp = 10.sp,
        fourteen_sp = 14.sp,
        fifteen_sp = 15.sp,
        thirty_six_dp = 36.dp,
        twenty_sp = 20.sp,
        fifty_dp = 50.dp,
        eighty_five_dp = 85.dp,
        twenty_six_dp = 26.dp,
        fifteen_dp = 15.dp,
        seven_dp = 7.dp,
        five_dp = 5.dp,
        zero_dp = 0.dp,
        three_dp = 3.dp,
        twenty_dp = 20.dp,
        two_dp = 2.dp,
        twelve_dp = 12.dp,
        thirteen_dp = 13.dp,
        hundredSeventyDp = 170.dp,
        pull_to_refresh_trigger_distance_dp = 100.dp,
        pull_to_refresh_offset_dp = 60.dp,
    account_landing_my_offers_image_height_dp = 178.dp,
    button_height_twenty_six_dp = 26.dp,
    fourteen_dp = 14.dp,
    eighteen_dp = 18.dp,
    one_twenty_dp = 120.dp,
    point_five_dp = 0.5.dp,
    one_point_five_sp = 1.5.sp

)

val sw420Dimensions = Dimensions(
    oneDp = 1.dp,
    dp24 = 24.dp,
    thirty_one_dp = 31.dp,
    letterspacing_029_sp = 0.29.sp,
    thirty_two_dp = 32.dp,
    icon_size_dp = 25.dp,
    twelve_sp = 12.sp,
    sixteen_sp = 16.sp,
    twenty_three_dp = 23.dp,
    eighteen_sp = 18.sp,
    fifty_seven_dp = 57.dp,
    sixty_dp = 60.dp,
    eighty_dp = 80.dp,
    eight_dp = 8.dp,
    sixteen_dp = 16.dp,
    zero_sp = 0.sp,
    one_sp = 1.sp,
    point_five_sp = 0.5.sp,
    ten_dp = 10.dp,
    six_dp = 6.dp,
    four_dp = 4.dp,
    thirteen_sp = 13.sp,
    fourteen_sp = 14.sp,
    fifteen_sp = 15.sp,
    thirty_six_dp = 36.dp,
    twenty_sp = 20.sp,
    fifty_dp = 50.dp,
    eighty_five_dp = 85.dp,
    twenty_six_dp = 26.dp,
    fifteen_dp = 15.dp,
    seven_dp = 7.dp,
    five_dp = 5.dp,
    zero_dp = 0.dp,
    three_dp = 3.dp,
    twenty_dp = 20.dp,
    two_dp = 2.dp,
    twelve_dp = 12.dp,
    thirteen_dp = 13.dp,
    hundredSeventyDp = 170.dp,
    pull_to_refresh_trigger_distance_dp = 100.dp,
    pull_to_refresh_offset_dp = 60.dp,
    account_landing_my_offers_image_height_dp = 190.dp,
    button_height_twenty_six_dp = 26.dp,
    fourteen_dp = 14.dp
)

val sw440Dimensions = Dimensions(
    oneDp = 1.dp,
    dp24 = 24.dp,
    thirty_one_dp = 31.dp,
    letterspacing_029_sp = 0.29.sp,
    thirty_two_dp = 32.dp,
    icon_size_dp = 25.dp,
    twelve_sp = 12.sp,
    sixteen_sp = 16.sp,
    twenty_three_dp = 23.dp,
    eighteen_sp = 18.sp,
    fifty_seven_dp = 57.dp,
    sixty_dp = 60.dp,
    eighty_dp = 80.dp,
    eight_dp = 8.dp,
    sixteen_dp = 16.dp,
    zero_sp = 0.sp,
    one_sp = 1.sp,
    point_five_sp = 0.5.sp,
    ten_dp = 10.dp,
    six_dp = 6.dp,
    four_dp = 4.dp,
    thirteen_sp = 13.sp,
    ten_sp = 10.sp,
    fourteen_sp = 14.sp,
    fifteen_sp = 15.sp,
    thirty_six_dp = 36.dp,
    twenty_sp = 20.sp,
    fifty_dp = 50.dp,
    eighty_five_dp = 85.dp,
    twenty_six_dp = 26.dp,
    fifteen_dp = 15.dp,
    seven_dp = 7.dp,
    five_dp = 5.dp,
    zero_dp = 0.dp,
    three_dp = 3.dp,
    twenty_dp = 20.dp,
    two_dp = 2.dp,
    twelve_dp = 12.dp,
    thirteen_dp = 13.dp,
    hundredSeventyDp = 170.dp,
    pull_to_refresh_trigger_distance_dp = 100.dp,
    pull_to_refresh_offset_dp = 60.dp,
    account_landing_my_offers_image_height_dp = 178.dp,
    button_height_twenty_six_dp = 28.dp,
    fourteen_dp = 14.dp,
    eighteen_dp = 18.dp,
    one_twenty_dp = 120.dp,
    point_five_dp = 0.5.dp,
    one_point_five_sp = 1.5.sp
)


val sw480Dimensions = Dimensions(
    oneDp = 1.dp,
    dp24 = 24.dp,
    thirty_one_dp = 31.dp,
    letterspacing_029_sp = 0.29.sp,
    thirty_two_dp = 32.dp,
    icon_size_dp = 25.dp,
    twelve_sp = 12.sp,
    sixteen_sp = 16.sp,
    twenty_three_dp = 23.dp,
    eighteen_sp = 18.sp,
    fifty_seven_dp = 57.dp,
    sixty_dp = 60.dp,
    eighty_dp = 80.dp,
    eight_dp = 8.dp,
    sixteen_dp = 16.dp,
    zero_sp = 0.sp,
    one_sp = 1.sp,
    point_five_sp = 0.5.sp,
    ten_dp = 10.dp,
    six_dp = 6.dp,
    four_dp = 4.dp,
    thirteen_sp = 13.sp,
    ten_sp = 10.sp,
    fourteen_sp = 14.sp,
    fifteen_sp = 15.sp,
    thirty_six_dp = 36.dp,
    twenty_sp = 20.sp,
    fifty_dp = 50.dp,
    eighty_five_dp = 85.dp,
    twenty_six_dp = 26.dp,
    fifteen_dp = 15.dp,
    seven_dp = 7.dp,
    five_dp = 5.dp,
    zero_dp = 0.dp,
    three_dp = 3.dp,
    twenty_dp = 20.dp,
    two_dp = 2.dp,
    twelve_dp = 12.dp,
    thirteen_dp = 13.dp,
    hundredSeventyDp = 170.dp,
    pull_to_refresh_trigger_distance_dp = 100.dp,
    pull_to_refresh_offset_dp = 60.dp,
    account_landing_my_offers_image_height_dp = 190.dp,
    button_height_twenty_six_dp = 28.dp,
    fourteen_dp = 14.dp,
    eighteen_dp = 18.dp,
    one_twenty_dp = 120.dp,
    point_five_dp = 0.5.dp,
    one_point_five_sp = 1.5.sp
)