package za.co.absa.openbankingapi.woolworths.integration.dto

class ErrorCodeList {

    private val mapABSAErrorCode = mapOf(
            Pair(1, "UNSUCCESSFUL"),
            Pair(100, "ACCESS CONTROL DEFAULT FAILURE CODE"),
            Pair(101, "ACCESS CONTROL FAILURE - USER HAS NOT OBTAINED THE SESSION AUTHENTICATION GROUPS REQUIRED FOR OPERATION"),
            Pair(102, "ACCESS CONTROL FAILURE - USER HAS NOT OBTAINED THE REQUEST AUTHENTICATION GROUPS REQUIRED FOR OPERATION"),
            Pair(103, "ACCESS CONTROL FAILURE - A USER HOLD DETECTED"),
            Pair(151, "IDP - SECURITY NOTIFICATION FAILURE - 2FA ENROLLMENT STATE THAT WILL NOT ALLOW A SURECHECK TO BE PERFORMED. RESPONSE TO USER TO BE SPECIFIC AROUND MANAGE DEVICE"),
            Pair(152, "IDP - SECURITY NOTIFICATION FAILURE - 2FA ENROLLMENT STATE THAT WILL NOT ALLOW A SURECHECK TO BE PERFORMED. RESPONSE TO USER TO BE SPECIFIC"),
            Pair(301, "IMS FUNCTION CALL - NO REPLY RECEIVED, TRANSACTION TERMINATED WITH UNKNOWN OUTCOME"),
            Pair(401, "PAYMENT DELAYED, PENDING REGISTRATION"),
            Pair(475, "NO REPLY RECEIVED FROM BANKSERV FOR THE INITIATION OF THE IIP (IMMEDIATE INTERBANK PAYMENT)"),
            Pair(480, "TRANSACTION RESULT PENDING FOR DELAYED IIP (IMMEDIATE INTERBANK PAYMENT) PAYMENT"),
            Pair(550, "ONBOARDING CLIENT POLLING - NO RESPONSE RECEIVED FROM SERVICE MANAGER, PLEASE POLL AGAIN"),
            Pair(601, "TRANSACTION RESULT PENDING FOR ACCOUNT VERIFICATION - PLEASE POLL AGAIN"),
            Pair(701, "OPTICAL CHARACTER RECOGNITION CLIENT POLLING - NO RESPONSE RECEIVED FROM OCR, PLEASE POLL AGAIN"),
            Pair(9999, "A SERIOUS ERROR HAS OCCURRED - ABANDON SHIP")
    )

    fun checkResult(statusCode: String): String? {
        val code = if (statusCode.isEmpty()) 0 else statusCode.toInt()
        return when (mapABSAErrorCode.containsKey(code)) {
            true -> mapABSAErrorCode[code]
            else -> null
        }
    }
}