package za.co.woolworths.financial.services.android.contracts

class FirebaseManagerAnalyticsProperties {
    companion object {

        const val WTODAYMENU = "GA_Event_ONE_WTODAYMENU"
        const val SHOPMENU: String = "GA_Event_ONE_SHOPMENU"
        const val MYCARTMENU: String = "GA_Event_ONE_MYCARTMENU"
        const val WREWARDSMENU: String = "GA_Event_ONE_WREWARDSMENU"
        const val MYACCOUNTSMENU: String = "GA_Event_ONE_MYACCOUNTSMENU"
        const val MYACCOUNTSSIGNIN: String = "GA_Event_ONE_MYACCOUNTSSIGNIN"
        const val WREWARDSSIGNIN: String = "GA_Event_ONE_WREWARDSSIGNIN"
        const val MYACCOUNTSREGISTER: String = "GA_Event_ONE_MYACCOUNTSREGISTER"
        const val WREWARDSREGISTER: String = "GA_Event_ONE_WREWARDSREGISTER"
        const val SHOPSEARCHBAR: String = "GA_Event_ONE_SHOPSEARCHBAR"
        const val SHOPBARCODE: String = "GA_Event_ONE_SHOPBARCODE"
        const val MYCARTEXIT: String = "GA_Event_ONE_MYCARTEXIT"
        const val MYCARTDELIVERY: String = "GA_Event_ONE_MYCARTDELIVERY"
        const val SHOPADDTOLIST: String = "GA_Event_ONE_SHOPADDTOLIST"
        const val SHOPNEWLIST: String = "GA_Event_ONE_SHOPNEWLIST"
        //const val SHOPSHOPPINGLIST: String = "GA_Event_ONE_SHOPSHOPPINGLIST"
        const val MYACCOUNTSSHOPPINGLIST: String = "GA_Event_ONE_MYACCOUNTSSHOPPINGLIST"
        const val MYCARTADDTOLIST: String = "GA_Event_ONE_MYCARTADDTOLIST"
        const val MYCARTCHECKOUT: String = "GA_Event_ONE_MYCARTCHECKOUT"
        const val MYCARTREMOVEALL: String = "GA_Event_ONE_MYCARTREMOVEALL"
        const val WREWARDSOVERVIEW: String = "GA_Event_ONE_WREWARDSOVERVIEW"
        const val WREWARDSVOUCHERS: String = "GA_Event_ONE_WREWARDSVOUCHERS"
        const val WREWARDSSAVINGS: String = "GA_Event_ONE_WREWARDSSAVINGS"
        const val WREWARDSFLIP: String = "GA_Event_ONE_WREWARDSFLIP"
        const val WREWARDSDESCRIPTION_VOUCHERDESCRIPTION: String = "GA_Event_ONE_WREWARDSDESCRIPTION"
        const val MYACCOUNTSSTORECARDAPPLYNOW: String = "GA_Event_ONE_MYACCOUNTS_SC_APPLYNOW"
        const val MYACCOUNTSCREDITCARDAPPLYNOW: String = "GA_Event_ONE_MYACCOUNTS_CC_APPLYNOW"
        const val MYACCOUNTSPERSONALLOANAPPLYNOW: String = "GA_Event_ONE_MYACCOUNTS_PL_APPLYNOW"
        const val MYACCOUNTSPERSONALLOANINCREASE: String = "GA_Event_ONE_MYACCOUNTS_PL_INCREASE"
        const val MYACCOUNTSPERSONALLOANMORE: String = "GA_Event_ONE_MYACCOUNTS_PL_MORE"
        const val MYACCOUNTSSTORECARDTRANSACTIONS: String = "GA_Event_ONE_MYACCOUNTS_SC_TRANSACTIONS"
        const val MYACCOUNTSSTORECARDSTATEMENTS: String = "GA_Event_ONE_MYACCOUNTS_SC_STATEMENTS"
        const val MYACCOUNTSPERSONALLOANTRANSACTIONS: String = "GA_Event_ONE_MYACCOUNTS_PL_TRANSACTIONS"
        const val MYACCOUNTSPERSONALLOANSTATEMENTS: String = "GA_Event_ONE_MYACCOUNTS_PL_STATEMENTS"
        const val MYACCOUNTSCREDITCARDBPI: String = "GA_Event_ONE_MYACCOUNTS_CC_BPI"
        const val MYACCOUNTSSTORECARDBPI: String = "GA_Event_ONE_MYACCOUNTS_SC_BPI"
        const val MYACCOUNTSPERSONALLOANBPI: String = "GA_Event_ONE_MYACCOUNTS_PL_BPI"
        const val ACCOUNTSEVENTSAPPEARED: String = "accounts_event_appeared"
        const val LOGIN: String = "login"
        const val SORTBY_EVENT_APPEARED: String = "GA_Event_ONE_SORTSFILTERS_BUT"
        const val SORTBY_EVENT_APPLIED: String = "GA_Event_ONE_SORTSFILTERS_OPTION"
        const val REFINE_EVENT_APPEARED: String = "GA_Event_ONE_SORTSFILTERS_REFINE"
        const val REFINE_EVENT_PROMO_ON: String = "GA_Event_ONE_SORTSFILTERS_PROMOON"
        const val REFINE_EVENT_PROMO_OFF: String = "GA_Event_ONE_SORTSFILTERS_PROMOOFF"
        const val REFINE_EVENT_SEE_RESULT: String = "GA_Event_ONE_SORTSFILTERS_SEERSB"
        const val REFINE_EVENT_BACK_BUTTON: String = "GA_Event_ONE_SORTSFILTERS_SEERSBB"
        const val SHOP_PRODUCTDETAIL_NUTRITIONAL_INFORMATION: String = "SHOP_PDP_NI"

        const val CRASH_CAUTION: String = "GA_Event_ONE_CRASH_CAUTION"
        const val SHOPMYLISTS: String = "GA_Event_ONE_SHOP_MYLISTS"
        const val SHOPMYORDERS: String = "GA_Event_ONE_SHOP_MYORDERS"
        const val BLOCK_CARD_CONFIRM: String = "GA_Event_ONE_MYACCOUNTSBLOCKCARDCONFIRM"
        const val BLOCK_CARD_CANCEL: String = "GA_Event_ONE_MYACCOUNTSBLOCKCARDCANCEL"
        const val ABSA_CC_SET_UP_PASSOCDE: String = "GA_Event_ONE_ABSA_CC_SETUP_PASSOCDE"
        const val ABSA_CC_COMPLETE_SETUP: String = "GA_Event_ONE_ABSA_CC_COMPLETE_SETUP"
        const val ABSA_CC_LOGIN_WITH_NEW_PASSCODE: String = "GA_Event_ONE_CC_LOGIN_WITH_NEW_PASSCODE"
        const val ABSA_CC_VIEW_STATEMENTS: String = "GA_Event_ONE_ABSA_CC_VIEW_STATEMENTS"
        const val ABSA_CC_SHARE_STATEMENT: String = "GA_Event_ONE_ABSA_CC_SHARE_STATEMENT"
        const val ABSA_CC_VIEW_INDIVIDUAL_STATEMENT: String = "GA_Event_ONE_ABSA_CC_VIEW_IND_STATEMENT"

        const val SHOPQS_ADD_TO_CART = "GA_Event_ONE_SHOPQS_ADD_TO_CART"
        const val SHOP_SCAN_CODE = "GA_Event_ONE_SHOPSCANCODE"
        const val MY_ACCOUNTS_CHAT_ONLINE = "MYACCOUNTS_CHAT_ONLINE"
        const val MY_ACCOUNTS_CHAT_OFFLINE = "MYACCOUNTS_CHAT_OFFLINE"
        const val MY_ACCOUNTS_CHAT_BREAK = "MYACCOUNTS_CHAT_BREAK"
        const val MY_ACCOUNTS_CHAT_END = "MYACCOUNTS_CHAT_END"

        const val MY_ACCOUNTS_VTC_GET = "MYACCOUNTS_VTC_GET"
        const val MY_ACCOUNTS_VTC_PAY = "MYACCOUNTS_VTC_PAY"
        const val MY_ACCOUNTS_VTC_HOW_TO = "MYACCOUNTS_VTC_HOWTO"

        const val MYACCOUNTS_ICR_GET_CARD = "MYACCOUNTS_ICR_GET_CARD"
        const val MYACCOUNTS_ICR_STORES = "MYACCOUNTS_ICR_STORES"
        const val MYACCOUNTS_ICR_LINK_START = "MYACCOUNTS_ICR_LINK_START"
        const val MYACCOUNTS_ICR_LINK_CARD = "MYACCOUNTS_ICR_LINK_CARD"
        const val MYACCOUNTS_ICR_LINK_CONFIRM = "MYACCOUNTS_ICR_LINK_CONFIRM"
        const val SHOP_MY_ORDERS_CANCEL_ORDER = "SHOP_MY_ORDERS_CANCEL_ORDER"
        const val WHATSAPP_PAYMENT_OPTION = "WHATSAPP_PAYMENT_OPTION"
        const val WHATSAPP_CONTACT_US = "WHATSAPP_CONTACT_US"
        const val WHATSAPP_CHAT_WITH_US = "WHATSAPP_CHAT_WITH_US"

        const val SHOP_SEARCH = "SHOP_Search"

        const val CC_ACTIVATE_NEW_CARD = "CC_ACTIVATE_NEW_CARD"
        const val CC_ACTIVATE_MY_CARD = "CC_ACTIVATE_MY_CARD"
        const val CC_ACTIVATION_COMPLETE = "CC_ACTIVATION_COMPLETE"

        const val SHOP_Click_Collect = "shop_click_collect"
        const val SHOP_Click_Collect_Prov = "shop_click_collect_prov"
        const val SHOP_Click_Collect_Stor = "shop_click_collect_stor"
        const val CART_BEGIN_CHECKOUT = "begin_checkout"
        const val CART_CHECKOUT_ABANDON = "ecommerce_abandon"
        const val CART_CHECKOUT_COMPLETE = "ecommerce_complete"
        const val CART_ORDER_CONFIRMATION = "ecommerce_purchase"
    }

    class PropertyNames {
        companion object {
            const val SUBURBNAME: String = "SUBURBNAME"
            const val VOUCHERDESCRIPTION: String = "VOUCHERDESCRIPTION"
            const val C2ID: String = "C2Id"
            const val ATGId: String = "ATGId"
            const val SORT_OPTION_NAME : String = "SORTBY_OPTION_NAME"
            const val DESCRIPTION : String = "DESCRIPTION"
            const val CANCEL_ORDER_TAP = "Cancel Order Tap"
            const val CONFIRM_CANCEL = "Confirm Cancel"
            const val CANCEL_CANCEL = "Cancel Cancel"
            const val CANCEL_API_SUCCESS = "Cancel API Success"
            const val CANCEL_API_FAILURE = "Cancel API Failure"
            const val CLOSE_FAILURE_CANCEL = "Close Failure Cancel"
            const val CANCEL_FAILURE_CALL_CENTRE = "Cancel Failure Call Centre"
            const val CANCEL_FAILURE_RETRY = "Cancel Failure Retry"
            const val ACTION = "ACTION"
            const val NUTRITIONAL_INFORMATION_PRODUCT_ID = "PRODUCT_ID"
            const val NUTRITIONAL_INFORMATION_FILTER_OPTION = "Filter_Option"
            const val ENTRY_POINT = "Entry_Point"
            const val DEEP_LINK_URL = "deepLinkUrl"
            const val provinceName: String = "province_name"
            const val storeName: String = "store_name"
            const val PERSONAL_LOAN_PRODUCT_OFFERING = "personal_loan"
            const val STORE_CARD_PRODUCT_OFFERING = "store_card"
            const val GOLD_CREDIT_CARD_PRODUCT_OFFERING = "gold_credit_card"
            const val SILVER_CREDIT_CARD_PRODUCT_OFFERING = "silver_credit_card"
            const val BLACK_CREDIT_CARD_PRODUCT_OFFERING = "black_credit_card"

        }
    }

    class ScreenNames {
        companion object {
            const val STARTUP: String = "Startup"
            const val WTODAY: String = "WToday"
            const val SHOP_BARCODE: String = "Shop Barcode"
            const val SHOP_BARCODE_MANUAL: String = "Shop Barcode Manual"
            const val SHOP_MAIN_CATEGORIES: String = "Shop Main Categories"
            const val SHOP_SUB_CATEGORIES: String = "Shop Sub Categories"
            const val PRODUCT_SEARCH: String = "Product Search"
            const val PRODUCT_SEARCH_RESULTS: String = "Product Search Result"
            const val PRODUCT_SEARCH_REFINEMENT: String = "Product Search Refinement"
            const val PRODUCT_SEARCH_REFINEMENT_CATEGORY: String = "Product Search Refinement Category"
            const val PRODUCT_DETAIL: String = "Product Detail"
            const val PRODUCT_DETAIL_IMAGE_ZOOM: String = "Product Detail Image Zoom"
            const val DELIVERY_LOCATION_HISTORY: String = "Delivery Location History"
            const val DELIVERY_LOCATION_PROVINCE: String = "Delivery Location Province"
            const val DELIVERY_LOCATION_SUBURB: String = "Delivery Location Suburb"
            const val CART_LIST: String = "Cart List"
            const val CART_CHECKOUT: String = "Cart Checkout"
            const val MY_ACCOUNTS: String = "My Accounts"
            const val PREFERENCES: String = "Preferences"
            const val HELP_SECTION: String = "Help Section"
            const val FAQ_LIST: String = "FAQ List"
            const val FAQ_DETAIL: String = "FAQ Detail"
            const val TIPS_AND_TRICKS_LIST: String = "Tips and Tricks List"
            const val TIPS_AND_TRICKS_DETAILS: String = "Tips and Tricks Details"
            const val STATEMENTS_LIST: String = "Statements List"
            const val STATEMENTS_EMAIL_CONFIRMED: String = "Statements Email Confirmed"
            const val STATEMENTS_ALTERNATIVE_EMAIL: String = "Statements Alternative Email"
            const val STATEMENTS_DOCUMENT_PREVIEW: String = "Statements Document Preview"
            const val SHOPPING_LISTS: String = "Shopping Lists"
            const val SHOPPING_LIST_ITEMS: String = "Shopping List Items"
            const val CREATE_SHOPPING_LIST: String = "Create Shopping List"
            const val SHOPPING_LIST_SEARCH_RESULTS: String = "Shopping List Search Results"
            const val SSO_SIGN_IN: String = "SSO Sign In"
            const val SSO_REGISTER: String = "SSO Register"
            const val SSO_LOGOUT: String = "SSO Logout"
            const val SSO_PASSWORD_CHANGE: String = "SSO Password Change"
            const val SSO_PROFILE_INFO: String = "SSO Profile Info"
            const val STORES_NEARBY: String = "Stores Nearby"
            const val STORES_SEARCH: String = "Stores Search"
            const val STORE_DETAILS: String = "Store Details"
            const val MESSAGES: String = "Messages"
            const val FINANCIAL_SERVICES: String = "Financial Services"
            const val FINANCIAL_SERVICES_STORE_CARD: String = "Financial Services Store Card"
            const val FINANCIAL_SERVICES_CREDIT_CARD: String = "Financial Services Credit Card"
            const val FINANCIAL_SERVICES_PERSONAL_LOAN: String = "Financial Services Personal Loan"
            const val HOW_TO_PAY: String = "Financial Services - How To Pay"
            const val TRANSACTIONS: String = "Transactions"
            const val BPI_OVERVIEW: String = "BPI Overview"
            const val BPI_DETAILS: String = "BPI Details"
            const val BPI_CLAIM_REASONS: String = "BPI Claim Reasons"
            const val BPI_DOCUMENTS_PROCESSING: String = "BPI Documents Processing"
            const val WITHDRAW_CASH: String = "Withdraw Cash"
            const val WITHDRAW_CASH_CONFIRMATION: String = "Withdraw Cash Confirmation"
            const val WITHDRAW_CASH_SUCCESSFUL: String = "Withdraw Cash Successful"
            const val DEBIT_ORDERS: String = "Financial Services - Debit Orders"
            const val CLI_WALKTHROUGH: String = "CLI Walkthrough"
            const val CLI_INSOLVENCY_CHECK: String = "CLI Insolvency Check"
            const val CLI_CONSENT: String = "CLI Consent"
            const val CLI_INCOME: String = "CLI Income"
            const val CLI_EXPENSES: String = "CLI Expenses"
            const val CLI_OFFER: String = "CLI Offer"
            const val CLI_POI_BANKS: String = "CLI POI Banks"
            const val CLI_POI_BANKS_ACCOUNT_TYPE: String = "CLI POI Banks Account Type"
            const val CLI_POI_BANK_ACC_NUMBER: String = "CLI POI Bank Account Number"
            const val CLI_POI_BANKS_AUTHORIZATION: String = "CLI POI Banks Authorization"
            const val CLI_POI_DOCUMENTS: String = "CLI POI Documents"
            const val CLI_POI_DOCUMENTS_UPLOAD: String = "CLI POI Documents Upload"
            const val CLI_POI_ERROR: String = "CLI POI Error"
            const val CLI_PROCESS_COMPLETE: String = "CLI Process Complete"
            const val CLI_PROCESS_COMPLETE_NO_POI: String = "CLI Process Complete No POI"
            const val WREWARDS_TIER_INFO: String = "WRewards Tier Info"
            const val WREWARDS_SIGNED_OUT: String = "WRewards Signed Out"
            const val WREWARDS_OVERVIEW: String = "WRewards Overview"
            const val WREWARDS_SIGNED_IN_LINKED: String = "WRewards Signed In Linked"
            const val WREWARDS_SIGNED_IN_NOT_LINKED: String = "WRewards Signed In Not Linked"
            const val WREWARDS_SAVINGS: String = "WRewards Savings"
            const val WREWARDS_VOUCHERS: String = "WRewards Vouchers"
            const val WREWARDS_VOUCHERS_BARCODE: String = "WRewards Vouchers Barcode"
            const val WREWARDS_TERMS_CONDITIONS: String = "WRewards Terms and Conditions"
            const val MAINTENANCE_MESSAGE: String = "Maintenance Message"
            const val DEVICE_ROOTED_AT_STARTUP: String = "Block Rooted Device"
        }
    }

    enum class EntryPoint(val value: String) {
        DEEP_LINK("Deep_Link"),MANUAL_SEARCH("Manual_Search"),QR_CODE("QR_Codes")
    }
}