package za.co.woolworths.financial.services.android.onecartgetstream.common.constant

object OCConstant {

    const val ACTION_START_RESUME_OC_NOTIFICATION_SERVICE = "ACTION_START_RESUME_OC_NOTIFICATION_SERVICE"
    const val ACTION_PAUSE_OC_NOTIFICATION_SERVICE = "ACTION_PAUSE_OC_NOTIFICATION_SERVICE"
    const val ACTION_STOP_OC_NOTIFICATION_SERVICE = "ACTION_STOP_OC_NOTIFICATION_SERVICE"

}